<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="srt-187" name="com.yanxiu.test.TestLogin" tests="5" failures="1" timestamp="26 Sep 2016 08:38:35 GMT" time="1.378" errors="0">
  <testcase name="testLogin" time="0.061" classname="com.yanxiu.test.TestLogin"/>
  <testcase name="testLogin" time="1.089" classname="com.yanxiu.test.TestLogin">
    <failure type="java.lang.AssertionError" message="com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance value (0) not found in enum (possible values: [1])
    level: &quot;error&quot;
    schema: {&quot;loadingURI&quot;:&quot;#&quot;,&quot;pointer&quot;:&quot;/properties/code&quot;}
    instance: {&quot;pointer&quot;:&quot;/code&quot;}
    domain: &quot;validation&quot;
    keyword: &quot;enum&quot;
    value: 0
    enum: [1]
---  END MESSAGES  ---
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance value (0) not found in enum (possible values: [1])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/properties/code"}
    instance: {"pointer":"/code"}
    domain: "validation"
    keyword: "enum"
    value: 0
    enum: [1]
---  END MESSAGES  ---
 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.yanxiu.test.BaseCase.runCase(BaseCase.java:190)
	at com.yanxiu.test.TestLogin.testLogin(TestLogin.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="0.034" classname="com.yanxiu.test.TestLogin"/>
  <testcase name="testLogin" time="0.042" classname="com.yanxiu.test.TestLogin"/>
  <testcase name="testLogin" time="0.152" classname="com.yanxiu.test.TestLogin"/>
</testsuite> <!-- com.yanxiu.test.TestLogin -->
